# syntax = docker/dockerfile:1.2
FROM integritee/integritee-dev:0.1.9 as build
WORKDIR /workspace
COPY . .
RUN cargo build --release

# produce a 'development' image
FROM integritee/integritee-dev:0.1.9
WORKDIR /node
COPY --from=build /workspace/target/release/ajuna-solo /node/ajuna
