name: Parachain to Docker Hub
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image tag in SemVer"
        required: true

env:
  IMAGE_REPO: ajuna
  IMAGE_NAME: parachain
  IMAGE_TAG: ${{ github.event.inputs.image_tag }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile.parachain
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
