name: Push to Docker Hub
on:
  push:
    tags:
      - polkadot-v*

env:
  IMAGE_REPO: ajuna
  IMAGE_NAME: solochain

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Get the image version
        run: echo "IMAGE_TAG=${GITHUB_REF/refs\/tags\/polkadot\-v/}" >> $GITHUB_ENV
      - run: echo "🐋 Building Docker images ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} 🐋 ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:latest 🐋"
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: docker/Dockerfile
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}, ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            features=solo
            bin=ajuna-solo

  notify:
    name: Notify on Slack
    runs-on: ubuntu-latest
    needs: [build-and-push-image]
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          job_name: Push to Docker Hub
          status: ${{ job.status }}
          fields: repo,pullRequest,commit,author,workflow,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
